use directs;

ALTER TABLE `USER`
	ADD `COMPANY_ID` INT(10) UNSIGNED NOT NULL;

-- ALTER TABLE `USER`
--  ADD CONSTRAINT `COMPANY_USER_ID`
--    FOREIGN KEY (`COMPANY_ID`)
--    REFERENCES `directs`.`company` (`cmp_id`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION;
