 CREATE TABLE direct 
  ( 
     id          BIGINT GENERATED BY DEFAULT AS IDENTITY, 
     name 		VARCHAR(255), 
     abv     	FLOAT
  );
  
   CREATE TABLE user 
  ( 
     id          INTEGER GENERATED BY DEFAULT AS IDENTITY, 
     username 		VARCHAR(255), 
     password     	VARCHAR(255)
  );
  
   CREATE TABLE CITIES 
  ( 
     id          BIGINT GENERATED BY DEFAULT AS IDENTITY, 
     name 		VARCHAR(255), 
     population   	INTEGER
  );
  
  
CREATE TABLE task 
  ( 
     id          INTEGER GENERATED BY DEFAULT AS IDENTITY, 
     description VARCHAR(255), 
     is_done     BOOLEAN, 
     target_date TIMESTAMP, 
     PRIMARY KEY (id) 
  );   